version: "3.8"
services:
  db:
    image: postgres:17.5
    container_name: db-images
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROGERNYVA
      POSTGRES_DB: photosnyva
    ports:
      - "54320:5432"
    volumes:
      - postgres-data-images:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  web:
    build: .
    environment:
      DB_USER: postgres
      DB_PASSWORD: ROGERNYVA
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: photosnyva
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  postgres-data-images:



